server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  devtools:
    restart:
      enabled: true

  profiles:
    active: local
  datasource:
#    url: jdbc:h2:tcp://localhost/~/querydsl
    url: jdbc:mysql://localhost:3306/study-security-jwt?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        #jpql 조회
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

jwt:
  token:
    secret: KdV0h1nSliuHZ3IbN1Ud9CYGp5vTia8/6y8SBbkeXV8=